# Generated by Django 6.0.4 on 2026-05-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0003_notification_savingsgoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('warning', 'Warning'), ('alert', 'Alert'), ('info', 'Info'), ('success', 'Success')], default='info', max_length=20),
        ),
    ]
